name: Deploy to Supabase

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 1.226.4 # Or your desired version

      - name: Log in to Supabase
        run: supabase login --token ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Link project
        env:
          SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}

      # This is the corrected deployment step
      - name: Deploy Edge Functions
        run: supabase functions deploy --no-verify-jwt --